### ISSUE TITLE
What does a value of 1 or 2 mean when returned?

### ISSUE THREAD

**Issue by dnicol** [nwtn/isflashinstalled.com#1]
Im trying to understand what the values of 1 or 2 mean for flash version.

**Comment by nwtn** [comment]
Can you paste in the complete set of values you get? I've never seen just a plain "1" or "2" on its own.

**Comment by dnicol** [comment]
We've realized its not the library its us. Ofc I realized that after I hit send!  This library is insanely valuable.

**Comment by nwtn** [comment]
OK great. Glad you're finding it helpful. I'll close the issue, but feel free to reopen if you need.
